package pl.przydan.paints;

public enum PaintNames {
    EXTENDER, GOLD, GREEN, GREEN_CHESPA, MAGENTA, ORANGE, ORANGE_LF, PROCESS_BLUE,
    PURPLE, RED032, RED485, REFLEX_BLUE, RHODAMINA, RUBIN_RED, SILVER, VIOLET, WARM_RED, WHITE,
    YELLOW, YELLOW_KONC
}
